### ISSUE TITLE
support gcc __int128 extension

### ISSUE THREAD

**Issue by TwoClocks** [Vexu/arocc#304]
clang is ok with this:
```c
typedef __int128 X;

_Static_assert(sizeof(X) == 16, "record X wrong sizeof");
_Static_assert(_Alignof(X) == 16, "record X wrong alignment");
```

**Comment by Vexu** [comment]
Done in 6abe3511759f9c57727bf9c8bb90878e27beedde, constant values for these are not yet supported.

**Comment by TwoClocks** [comment]
This code snippet still fails the assert for `sizeof()` for me.

**Comment by Vexu** [comment]
Copy-paste mistake, fixed in 70505d4965a5e5670a2a2698a12ae422339bfcbe.

**Comment by TwoClocks** [comment]
that works. Here is the next thing:
```c
typedef unsigned __int128 Y;
```
yields
```
0050_test.c:30:18: error: cannot combine with previous 'unsigned' specifier
typedef unsigned __int128 Y;
```

**Comment by Vexu** [comment]
I forgot to add the combination logic in both orders, fixed in d52a46cc5274f233ec3937aad4976a1384559168.
